### ISSUE TITLE
Complete the SSR for the ATO.

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#124]
We need to complete the System Security Review (SSR) document for the ATO.  The following are items to be included in the SSR along with tentative assignments (to be discussed further).

- [x] PIA updated (Theresa)
- [ ] We need the review/approval workflow processes documented, as well as the process for assigning permissions to the workflow. - Fureigh/18F
- [ ] We need the auditable events documented and understand where/how the events are recorded (what is recorded and where and how do we access the information if needed, and who can access that information).  - Fureigh/18F
- [ ] We need the type of users and user privileges documented.  - Fureigh/18F, DAS
- [ ] We need the data flow documented by describing the flow of data in and out of system boundaries and creating a data flow diagram. This should include protections implemented at all entry and exit points in the data flow as well as internal controls between different user types. - Matt, DIS - maybe some input from Fureigh
- [ ] We need to detail how accounts are created in beta.nsf.gov.  How a user authenticates to beta.nsf.gov (probably through NSF ADFS or OpenAM services).  How users are assigned roles and/or permissions in beta.nsf.gov.  How is it determined which users get which roles (approval process for granting roles). -  Fureigh/18F, Matt
- [ ] We need to document the systems configuration management process, including the change management process, inventory control, baseline configuration, and unauthorized change detection.
- [ ] We need to document the system’s contingency plan and disaster recovery plan, including the system backup and recovery procedures, as well as describing how backup information is stored, transmitted, and protected. - Fureigh/18F, cloud.gov
- [ ] We need to document the system’s incident response plan and procedures. - Fureigh/18F, cloud.gov, Matt, DIS
- [ ] We need to document the system’s communication protection mechanisms including any use of cryptography. - Fureigh/18F, Matt, DIS
- [ ] We need to document the system’s patch and vulnerability management procedures. How fast do patches need to be implemented? - Fureigh/18F, Matt, DIS
- [ ] We need to complete a network architecture diagram - Matt, DIS - maybe some input from Fureigh

Documents for reference include the **QA docs** and the **MVP scoping document**

**Comment by mtboesch** [comment]
We need to complete the System Security Review (SSR) document for the ATO.  The following are items to be included in the SSR along with tentative assignments (to be discussed further).

- [ ] We need the review/approval workflow processes documented, as well as the process for assigning permissions to the workflow. - Fureigh/18F
- [ ] We need the auditable events documented and understand where/how the events are recorded (what is recorded and where and how do we access the information if needed, and who can access that information).  - Fureigh/18F
- [ ] We need the type of users and user privileges documented.  - Fureigh/18F, DAS
- [ ] We need the data flow documented by describing the flow of data in and out of system boundaries and creating a data flow diagram. This should include protections implemented at all entry and exit points in the data flow as well as internal controls between different user types. - Matt, DIS - maybe some input from Fureigh
- [ ] We need to detail how accounts are created in beta.nsf.gov.  How a user authenticates to beta.nsf.gov (probably through NSF ADFS or OpenAM services).  How users are assigned roles and/or permissions in beta.nsf.gov.  How is it determined which users get which roles (approval process for granting roles). -  Fureigh/18F, Matt
- [ ] We need to document the systems configuration management process, including the change management process, inventory control, baseline configuration, and unauthorized change detection.
- [ ] We need to document the system’s contingency plan and disaster recovery plan, including the system backup and recovery procedures, as well as describing how backup information is stored, transmitted, and protected. - Fureigh/18F, cloud.gov
- [ ] We need to document the system’s incident response plan and procedures. - Fureigh/18F, cloud.gov, Matt, DIS
- [ ] We need to document the system’s communication protection mechanisms including any use of cryptography. - Fureigh/18F, Matt, DIS
- [ ] We need to document the system’s patch and vulnerability management procedures. How fast do patches need to be implemented? - Fureigh/18F, Matt, DIS
- [ ] We need to complete a network architecture diagram - Matt, DIS - maybe some input from Fureigh

**Comment by mtboesch** [comment]
@trinehar can you take on the PIA assignment for beta.nsf.gov?

**Comment by fureigh** [comment]
@mtboesch Let's pair on this — likely in the next sprint.

**Comment by cmc333333** [comment]
High-level notes

## Audit and Accountability
Imagine that something bad has happened, maybe the website's been defaced or the system is under attack. What are the tools we'd used to figure out what happened?

Significant application events are logged to the database. The database is encrypted at rest.
* [ ] For the events, verify that we're recording:
    * Event type
    * Date/time
    * "where" the event occurred - need to dig in to see what this means
    * "source" of the event - need to dig in to see what this means
    * success/failure of action (notably, around authentication)
    * identity of the user/subject of the event (i.e. one of username, ip addy, etc.)
* [ ] Verify we're generating events for _attempts_ at
    * Authentication (logging in)
    * Authorization (permissions checks)
    * "Privileged" operations (can probably be bundle into the former)
    * Access to the logs should also be logged...
* [ ] Define where (if) general access logs are being stored
* [ ] Verify retention period (must be >= 1 yr). This might be a Drupal setting or it could be a policy

Cloud.gov will store anything from stdout/stderr in its own logging system, which is available for inspection through Kibana. This _may_ include access events, system exceptions, etc. depending on what the application is outputing.
* [ ] Check where access/error logs (e.g. from Apache) are tracked. ATO docs don't explicitly mention this, but it may come up.

At a separate layer of logging, cloud.gov will track infrastructure events (heartbeat checks, application deploys, application deaths, etc.). These are accessible through Kibana.
* [ ] Check if logs are encrypted at rest (90% positive they are)

At the platform level, cloud.gov tracks when someone attempts to log in (to cloud.gov, not the Drupal app), when user roles are changed, when a user is added, etc. These are not accessible through Kibana (they require making a request to cloud.gov folks, if I understand correctly).
* [ ] Check if logs are encrypted at rest (90% positive they are)

## Configuration Management
Configuration Management is all about preventing a scenario where the lone wolf developer is the only one who knows what's going on. We're looking for reproducibility (returning the app to a baseline) and decision tracking (so we have a record of when configs are changing).

There are several layers of configuration we'll want to account for. At the infrastructure level, we're using cloud.gov's PHP buildpack as a baseline configuration for Linux and PHP. We use the latest release (they're updated by the cloud.gov team for security) whenever deploying. Those images are managed (and secured) by cloud.gov. Here, we'll largely be linking to cloud.gov docs.
* [ ] Confirm we're using the current PHP buildpack (and that we are not pinning it)

The systems architecture including number of instances, which services (e.g. database) are attached, environment variables, etc. will need to be tracked in a manifest file. This manifest file will be hosted in Github so we can see how it has changed over time (and who has made the modifications). We will have a policy that all architecture changes are applied to this manifest (rather than configured dynamically).
* [ ] Work w/ @fureigh to setup that manifest file

Changes to the application code (including updating dependencies) are tracked via GitHub. Our general policy will be that code is not deployed unless it matches what's present in GitHub. Ideally, we'd have a technical restriction that deploy code could only come from our continuous integration system, but if that's far off, we can start with a policy.
* [ ] Cost-benefit analysis of deploying from CI

Drupal's configuration should likewise be tracked within the Github repository.
* [ ] Ensure config is loaded at app boot
* [ ] Discuss whether restricting config changes in prod is viable
* [ ] Discuss how config changes are logged if they're possible in the prod environment

In past ATOs, I've needed to set up a daily (or some other periodic frequency) app redeploy to ensure that we're frequently returning to the app's baseline configuration. This would wipe out actions performed by `cf ssh`ing, edits to the app code, some of the architecture changes, and ensures the latest buildpack is being used. It wouldn't touch Drupal configs stored in the db.
* [ ] Discuss viability here. It'd make a stronger case for the ATO, but it could also be a policy

## Contingency Planning
Cloud.gov can detect when an application has crashed (its main process ended), and will automatically restart the crashed app. We have only one instance, so this will create a little downtime. Of course, the action which led to the crash can be repeated, which will likely result in the same crash. This restarting should accommodate our needs around day-to-day errors.

Code and configuration will be stored in GitHub and therefore easy to restore in the case of catastrophic application failure (e.g. cloud.gov loses all of its app data).

Cloud.gov keeps a [daily backup](https://cloud.gov/docs/services/relational-database/#backups) of the database, which should account for sudden, catastrophic errors (e.g. accidentally dropping an important table). It does not, however, satisfy a longer-term backup strategy. We can likely punt on that for now.

## Incident Response
* [ ] How are we alerted of errors?
* [ ] Do we want something like New Relic?

## System and Communications Protection
For the most part, we can assume TLS between all system components (including internal to cloud.gov). Our database is encrypted at rest. We'll just need to type that all up.

## Patch and Vulnerability Management
At the infrastructure level (Linux, PHP), we can rely on cloud.gov (and drop in links to their docs). Reminder that we need to trigger a redeployment to use the updated images and buildpacks.

At the library level we'll need to define how we get alerted of security updates and how quickly we respond to them (i.e. a policy). On other projects, I'd recommend Synk.io, but I believe Drupal handles some of this security checking automatically.
* [ ] Spell out where we get alerts from
* [ ] Create a policy for how to respond to alerts, including how quickly we expect rectification

**Comment by cmc333333** [comment]
## Audit and Accountability

Significant application-level events are logged to the database; these include:
* creation/deletion of users
* successful/unsuccessful login attempts
* creation/modification/deletion of content
in addition to various debugging logs.

For each event, we log
* Event category (e.g. "user" related, "content" related, etc.)
* Date + time of event
* User who triggered the event ("Anonymous" if we no user is logged in)
* Url that triggered the event (when applicable)
* Event summary (e.g. "New user: [name]" or "Session opened for [name]" or "Login attempt failed from [ip]")
* Event severity (e.g. notice, warning)
* IP of the individual which triggered the event

These events are encrypted at rest (along with all of the database content) and not accessible/deletable by [**application users**] (which do not have the requisite permissions). They can, however, be exported and/or cleared by [**application developers**]. These events are configured to be stored indefinitely.

Below the application, we track various platform logs via cloud.gov. These include
* Apache httpd access/exception logs (which pages were requested, when, what errors occurred?)
* Application deployments/deaths
* Heartbeat health checks

These logs are accessible to [**application developers**] by logging into cloud.gov and using their [Kibana interface](https://cloud.gov/docs/apps/logs/#web-based-logs-with-historic-log-data). Logs are kept for 180 days and encrypted at rest and only transmitted over TLS. Permission to access these logs is restricted by cloud.gov roles.

Finally, at the cloud.gov authentication level, login attempts and permission changes are stored within the cloud.gov infrastructure. These are not immediately accessible to our team, but [can be retrieved by the cloud.gov team](https://cloud.gov/docs/compliance/for-assessors/#auditing-login-attempts). This data is encrypted at rest.

### Warnings (Internal)
* We don't log changes to user permissions within Drupal. This may be fine as long as we don't make a distinction between these permissions in the "Types of Users" section.
* Cloud.gov only keeps logs for 180 days. If the 1 year requirement in the ATO is a hard requirement, we need to set up some sort of export.

### TODOs (Internal)
* [ ] Configure Drupal to retain logs indefinitely (it's currently set to store only the most recent 1000)
* [ ] Prevent Drupal users from having access to dblogs. See [bug report]
(https://www.drupal.org/project/drupal/issues/1635646)

**Comment by cmc333333** [comment]
Followup from a conversation we just had, we have a user need to track when another user was granted permissions. This not only means we need to log those changes, it might also mean we need to allow Drupal users to view those logs. The issue I'm concerned about at the moment is that the same permission to view logs allows a user to _delete_ those logs.

**Comment by cmc333333** [comment]
## Configuration Management

We have a few different types of configuration at different layers of the stack. At the infrastructure level, we're using cloud.gov's baseline configuration of Linux and its PHP "buildpack", which are frequently updated as vulnerabilities are published and resolved. See cloud.gov's [documentation on this topic](https://cloud.gov/overview/technology/responsibilities/) for an overview. Every time code is deployed, it will be running on the latest baseline images, which are managed (and secured) by the cloud.gov team.

The system architecture (an inventory of all running services, amount of ram, environment variables, etc.) as encoded in a "manifest" file, Drupal configuration (including content types, user groups, etc.), application-level libraries (e.g. version of Drupal), and custom code are all tracked in an authoritative code repository. This is currently hosted on GitHub, which provides a clear log of all the changes to this system over time, including who made the modifications and their reasoned explanations.

While it is possible for a [**system administrator**] to modify the running configuration outside of GitHub, our policy rejects this practice outside of what's needed for debugging. As a mitigating enforcement mechanism, each software deployment will effectively reset the system to match the deployed configuration/code; this is also a mitigation against malicious intruders. In a future state, we anticipate deploying automatically on a frequent basis to further enforce this limitation.

## Warning (Internal)
* This doesn't define a _policy_ for how configuration changes are made. This policy could be that a second developer reviews the change, or that each change has a corresponding request ticket, or that the changes are part of a published roadmap, etc. etc.

## TODOs (Internal)
* [ ] Update the GitHub repo to include a manifest and the Drupal config export
* [ ] Define that change policy

**Comment by cmc333333** [comment]
## Types of Users

### Application Users
* *Public* - **External** users have no permissions to update beta.nsf.gov content. Further, they only have permissions to see a subset of the content (the "published" content). They access the application from the public internet.
* *Content editor* - These **internal** users have permissions to add, edit, publish, and delete different types of content. Individuals are assigned "roles", which further restrict access to a subset of content and content actions. Roles are created by site developers, and granted to individuals by user administrators.
* *User administrator* - These **internal** users can add, modify, and delete content editors and other users administrators, including granting content editors different "roles". Due to these permissions, it'd be accurate to say that user administrators have a superset of the permissions content editors do.

### Developers & Ops
* *Site developer* - These **internal** users can modify the code base and its configuration. They can add Drupal modules and write custom functionality, including the configuration of new _types_ of content (and the associated role permissions and workflows). Site developers make these changes to the underlying code base through GitHub pull requests.
* *System administrator* - These **internal** users have permissions to deploy and debug code running in our staging and production cloud.gov environments. They can manipulate the *live* application code when necessary, but we anticipate that to be an uncommon case. See also "Configuration Management" for more. System administrators are the only user type with access to our Platform-as-a-Service, cloud.gov.

## Access Controls

### Account Management

Individuals become *system administrators* upon being granted cloud.gov permissions from an existing system administrator. We anticipate needing a very limited number of system administrators at a given time, so this title/these permissions will only be assigned on an as-needed basis and with discussion of the larger project team. These permissions are reviewed at least annually, though we also remove the permissions/account when an administrator off-boards the project. We can request an audit log on modifications to account permissions from the cloud.gov team for all events within the prior 180 days.

Paralleling this, users become *site developers* by being given write access to our GitHub repository. This access is only granted by other site developers on an as-needed basis. These permissions are also reviewed at least annually, though again, we remove these permissions as a developer off-boards the project. GitHub permissions changes are logged forever, and accessible via the organization owner; permissions events for a specific user (including granting/revoking permissions for others) can be found on their security page (though the number of entries is limited).

Likewise, users become *user administrators* by being granted this permission within the beta.nsf.gov Drupal instance by an existing user administrator. This access is granted as needed, through the Drupal interface. Existing permissions are reviewed at least annually, and removed when a user off-boards the project. We do not currently log when a user specifically enters this role, though we do log when a user is created, edited, and deleted.

Finally, *content editors* are granted access to the beta.nsf.gov Drupal instance by user administrators. This is granted as needed, through the Drupal interface. As with the other roles, permissions are reviewed at least annually, and accounts removed when a user off-boards the project. The creation, modification, and deletion of these users is logged to the database (see "Audit and Accountability"). Further, content editors are granted specific "roles" to modify content of to-be-determined types by user administrators. These permissions restrict individuals to editing a subset of the site's total content. We do not currently log role modifications (though we do log that a user was modified).

### Authentication
Both *content editors* and *user administrators* log in to the beta.nsf.gov Drupal instance via NSF's Active Directory Federation Services (ADFS), which imposes NSF's org wide restrictions on multi-factor authentication, password strength, etc. To detail the SAML/ADFS interaction:
1. A user attempts to access a restricted portion of the Drupal site via their browser
1. The Drupal site returns a redirect to NSF's ADFS service, containing serialized data as used in following step.
1. The user authenticates to ADFS. As a last step, ADFS generates an HTML form which will POST values describing the user and signs this content.
1. Drupal confirms the signature and logs the user in (if they exist in the Drupal system) and redirects them to their original destination.

The *system administrator* role is similarly authorized to access cloud.gov via NSF's ADFS service. These users can begin the authentication process in one of two ways. They may try accessing a restricted area of cloud.gov's site (e.g. their web-based dashboard, or their Kibana-based log viewer), in which case they will be redirected to cloud.gov's login page. At this point, they must select an authentication provider. As only NSF users will have access to this portion of cloud.gov, users must select the NSF ADFS provider and follow the steps described above, eventually redirecting to the restricted system. If the user is instead using the command line, they will call the special

cf login --sso

command, which directs the user to visit an authentication page on cloud.gov, tailored for this use case. As with the web authentication, the user must select NSF's ADFS and log in using it. Then, cloud.gov will generate a unique token, which should be pasted into the running terminal. This allows the command line program to log in and perform actions as the authenticated user.

*Site developers* authenticate to GitHub using its multi-factor authentication scheme. Our policy requires all GitHub users who have permissions to our repository to use multi-factor auth. Further, code may only be merged through GitHub's web interface via the [protected branches](https://help.github.com/articles/about-protected-branches/) feature. This prevents developers from modifying the code base without first logging in to the multi-factor system.

Our policy requires all users access these services from within the NFS network (i.e. behind the TIC). Currently, restricted Drupal pages are only accessible through the NFS network (as defined by a restriction on originating IP). We intend to apply a similar scheme for system administrators, but that is an ongoing discussion with the cloud.gov team.

## Warnings (internal)
* This relies on GitHub as an authorization tool, which might be a non-starter. If that's the case, we may need to give more responsibilities to the "System administrator" and effectively say that that role is also verifying the code to be deployed hasn't been tampered with.
* This asserts that our policy is to review each role permission at least annually. Can we commit to that?
* Similarly, this is only loosely sketching out a policy around granting user access. Do we want to require that there's an issue in the jira, a conversation in slack, etc. etc.?

## TODOs (internal)
* [ ] Implement ADFS for Drupal
* [ ] Implement ADFS for cloud.gov
* [ ] Enable protected branches for master/dev/what-have-you
* [ ] Implement IP-based restrictions in Drupal

**Comment by cmc333333** [comment]
## Contingency Planning
As a first layer of defense, our system architecture requires a minimum of two running instances of the Drupal application. This aids load balancing, but also ensures that if one instance is down, traffic is routed to the second. Cloud.gov detects application crashes (as indicated by a dead primary process), and will automatically restart the crashed app. Combined, this significantly reduces the amount of downtime due to system errors. For a given deployment, application code and configuration are stored securely within cloud.gov, allowing these system restarts to be completely automated.

The codebase and system configuration (including change history) is stored within an authoritative GitHub repository, which ensures the application can be rebuilt from scratch if necessary. Due to the distributed nature of git, each site developer also maintains a copy of the repository's history, accounting for an additional safety net, should GitHub be unavailable. This source code is all publicly accessible, removing the need for additional protections.

The database (which stores content, users, their permissions) is an instance of Amazon Web Services' [Relational Database Service](https://aws.amazon.com/rds/) via cloud.gov. It is configured to store an encrypted, [daily snapshot](https://cloud.gov/docs/services/relational-database/#backups) retrievable by the cloud.gov team. So long as they're informed of a sudden, catastrophic error (e.g. accidentally dropping an important table), they can restore from the most recent backup. We do not currently have policies around long-term data retention.

### Warnings (Internal)
* Not having a long term backup strategy may be an issue. We might be able to mitigate it by describing how the content can be easily re-imported from other sources.

### TODOs (Internal)
* [ ] Ensure instance count is 2+

**Comment by cmc333333** [comment]
@mtboesch - Every org's a bit different on where they need details for these types of diagrams. I've fleshed out the cloud.gov side a bit and added a reference to social media, but this may need to be mashed up with your existing diagrams around ADFS.

## Network Architecture
![nsf network architecture](https://user-images.githubusercontent.com/326918/37166760-fa61971e-22cd-11e8-834b-98d58fd51e0f.png)

* *Elastic Load Balancer* - Cloud.gov's primary entry points are Amazon Web Service (AWS) load balancers. These may be further shielded by AWS's content distribution networks, depending on configuration. These systems evenly distribute traffic to cloud.gov's "router" services.
* *Cloud.gov Router* - Cloud.gov maintains a mapping between domains and the appropriate app backends; they pass traffic along to our app based on requested domain name.
* *Drupal (Web)* - The workhorse of our application, the web instances are PHP-based Drupal installs running on cloud.gov's infrastructure. They receive and respond to web traffic by querying and writing to the database. All relevant web traffic (including authenticated users) hit these instances. We run at least two instances in production.
* *Drupal (Cron)* - We also run a non-routable (i.e. inaccessible from the web) worker instance whose sole responsibility is to run routine Drupal scripts around importing new content, deleting stale user sessions, etc. It will make requests to social media platforms to retrieve content for publication. Like the web instances, it runs on cloud.gov's PHP buildpack.
* *MySQL* - Our database backend. This is only accessible from the connected Drupal instances. It stores all of our content, user sessions, assigned user permissions, etc.
* *Secrets Store* - "Secrets" - sensitive configuration data which is not stored in our code repository - are housed in an (encrypted) cloud.gov [user provided service](https://docs.cloudfoundry.org/devguide/services/user-provided.html). These are injected into their associated apps as environment variables at app startup.

### TODOs (Internal)
* [ ] Add cron service
* [ ] Map out all the secrets we need to track

**Comment by cmc333333** [comment]
## Incident Response
The beta.nsf.gov system follows the NSF's Computer Security Incident Response Procedure. Our primary source of incident detection is a monthly log review, which requires system administrators search over logs for security events (account creation, modification, ssh access), deployments, and application exceptions and compare them to known records. When unexplainable discrepancies are discovered, the NSF incident response procedure is followed.

Each deployment builds from a fresh system image, returning the application to a known good configuration. This reduces the need for complex containment, eradication, & recovery steps. The database is _not_ modified during deployment, however, so assigned user permissions will _not_ be reset. In this scenario, the recovery procedure (as part of incident response) will include a user administrator adjusting permissions within Drupal's admin. Similarly, site developers and system administrators will modify the permissions of their respective users when uncovering unexpected assignments.

### Warnings (Internal)
* The Computer Security Incident Response Procedure involves several roles that'll need to be assigned. While the majority will go to DIS folks, it'd be a good idea to remind the system owner of what they're signing on for.
* This makes a claim that our admins will review logs monthly. I'll write up some docs, but heads up that I'm signing us up for more work.
* This is a *very* light (and very manual) incident detection policy. I'll propose a few alternatives:
    * Drupal has a handful of modules which will send emails when particular categories of logs are generated. This doesn't cover the full stack (Drupal won't know if something failed below it), but do cover the majority of the application.
    * GSA's standardized on [New Relic](https://newrelic.com/) APM (which captures application errors, slow-downs, etc.) and Synthetics (which monitors uptime). These systems can get pricey, but they're also on their way towards FedRAMP.
    * [Sentry](https://sentry.io) is an alternative to New Relic that has a (self-hosted) open source option. This would be worth considering if you all have the capacity to maintain it. This is similar to a buy/build decision -- buy or maintain.
    * There are various uptime monitoring solutions, such as [Pingdom](https://www.pingdom.com/), [Uptime](https://uptime.com/), etc. that might be worth considering. These send notifications when configured urls/paths aren't accessible.

### TODOs (Internal)
* [ ] Document log review procedures
* [ ] Discuss alerting policies

**Comment by cmc333333** [comment]
## System and Communications Protection

As described in the network diagram all external communications (and many internal connections) are encrypted via TLS. Notably, all web requests to and from cloud.gov are over HTTPS. Further, within cloud.gov, communications between the application instances and the database are also encrypted in transit via TLS. Traffic between load balancers and application instances is generally not encrypted, but secure within the cloud.gov boundary. Per cloud.gov's [documentation](https://cloud.gov/docs/apps/custom-domains/#how-to-set-up-a-custom-domain) DNSSEC will be configured (post deployment).

Our MySQL database is configured to [AES-256 encrypt](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html) data at rest (on disk). Similarly, the secrets store is managed by cloud.gov in an encrypted RDS instance (along with other sensitive, infrastructure configurations). The application does not store data (beyond source code, cache files, etc.) on the local file system.

### Warnings (Internal)
* I've assumed that DIS will set up the DNSSEC records. If that's not the case, we'll want to remove those comments.

### TODOs (Internal)
* [ ] Confirm we don't have file uploads. If we *are* storing data in S3, we'll need to modify the network diagram, may need to discuss encryption, and may need to mention authentication.

**Comment by cmc333333** [comment]
## Patch and Vulnerability Management

At the infrastructure layer (covering our base Linux image, PHP version, etc.), we rely on the cloud.gov team to [continually update](https://cloud.gov/overview/technology/responsibilities/) the Linux kernel and apply patches to the PHP buildpack. Each deployment we make builds off the most recent provided images, ensuring a steady stream of updates.

At the application layer, our software libraries (including Drupal) are defined in a Composer "[lock](https://getcomposer.org/doc/01-basic-usage.md#installing-with-composer-lock)" file to ensure all library versions are consistent between deployments and all dependency updates are intentional. One of the tasks of our "Drupal (Cron)" worker is to query Drupal.org's module database to check for outdated modules, and in particular, modules with a pending security update. The worker is configured to send an alert about module updates to the site developers when discovered. We anticipate updating all our dependencies on a quarterly basis, but responding to security alerts within a week of notification.

When site developers want to update a library, they use [Composer](https://getcomposer.org/) to modify the "lock" file, commit that to the authoritative GitHub repository, and deploy. During its deployment process, cloud.gov installs the library versions as defined in the lock file, ensuring that the update is propagated.

### Warnings (Internal)
* Again, I'm defining a rough policy in terms of timelines for response. We can tweak that if desired, but this is roughly what I recommend on other projects.
* There _is_ a gap here around composer dependencies which aren't covered by Drupal's update manager. Any PHP modules we install which aren't in Drupal's module database won't be covered. I'm not certain if we have any such modules, but if so, I'd recommend a tool like [Gemnasium](gemnasium.com) (which is GSA's current service, but which is shutting down in April), [Snyk](snyk.io) (which GSA will likely move to), or other dependency tracking services.

### TODOs (Internal
* [ ] Ensure Drupal's configured to send those emails
* [ ] Figure out whether Drupal's checks cover all libs

**Comment by cmc333333** [comment]
We'll be using DIS's internal tools to track uptime, app monitoring. No need for discussion on alerting.

**Comment by cmc333333** [comment]
Session data is, in fact, stored in the db.

**Comment by cmc333333** [comment]
We *are* storing uploaded files, so we need to tweak the SSR a little bit.

## Network Architecture
![nsf network architecture 1](https://user-images.githubusercontent.com/326918/37312412-5a3ea50e-2621-11e8-81a9-7debc9afa8e6.png)

* *Elastic Load Balancer* - Amazon Web Service (AWS) restricts all access to its services (including Cloud.gov's primary entry points) behind load balancers. These may be further shielded by AWS's content distribution networks, depending on configuration. These systems evenly distribute traffic to cloud.gov's "router" services, and allow access to S3 files if given the appropriate credentials.
* *S3* - The "Simple Storage Service" stores files uploaded by users (e.g images, pdfs, etc.) and is only writable through our Drupal apps. By default, files stored in S3 are publicly accessible. Though we don't use this feature at the moment, we have the option of restricting access to these files as needed.

## System and Communications Protection

The S3 files are also [AES-256 encrypted](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html) at rest.

## TODOs (Internal)
* [ ] Configure flysystem with to use S3's encryption (should be a one-liner)

**Comment by cmc333333** [comment]
One more around S3:

## Contingency Planning

Data in S3 is configured with the "Standard" storage class, which translates to 99.999999999% durability. Files added through the Drupal interface are stored in S3, and are not generally deleted (though future modules may use that capability). As such, we do not have policies to store backups or archives of S3 files.

**Comment by mtboesch** [comment]
The SSR was approved for cloud.gov back in March.  We will create a new ticket for the SSR that CA will work on.
