### ISSUE TITLE
BP: As a member of the team, I want to have a sense of two alternative design directions that represent how NSF wants to be perceived by external audiences. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#244]
## User story
BP: As a member of the team, I want to have a sense of two alternative design directions that represent how NSF wants to be perceived by external audiences. 
  
## Acceptance criteria
- [x] We have an idea of two alternative design directions.   These are the design directions that represent how NSF wants to be perceived by external audiences.  (Austin / Ellen)
- [x] Summarize interview comments (dependency #243 )
- [x] Review survey data (dependency #242)
- [x] Synthesize workshop comments (dependency #243)
- [x] Identify candidate directions

Note: this is a longer term task likely to stretch beyond the initial sprint.
