### ISSUE TITLE
As a team member, I want an idea of how our current progress matches up against the SOW so we can see how well we're tracking against anticipated and current needs. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#251]
## User story
As a team member, I want an idea of how our current progress matches up against the SOW so we can see how well we're tracking against anticipated and current needs. 
  
## Acceptance criteria
- [ ] Create timeline / deliverable matrix
- [ ] Match against the sprint outline that Kate / Austin had worked on previously
- [x] Confirm progress against what we said we’d do, and align to where we are currently and where we hope to be
