### ISSUE TITLE
As a member of the CivicActions team, I want to complete planning for the initial CivicActions discovery/engagement roadmap to get a better sense of priorities for the first part of this engagement.

### ISSUE THREAD

**Issue by kategarklavs** [18F/nsf#273]
## User story

As a member of the CivicActions team, I want to complete planning for the initial CivicActions discovery/engagement roadmap to get a better sense of priorities for the first part of this engagement. 
  
## Acceptance criteria
- [ ] Figure out budgeting for onsite work (CA)
- [ ] Nail down a date for onsite work (all teams)
- [ ] tk

## Definition of done
- [ ] Budget for onsite work is determined.
- [ ] Onsite work dates are chosen.
- [ ] Travel arrangements are made.
