### ISSUE TITLE
As a team member, I would like an updated acquisitions roadmap so that I can plan accordingly. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#71]
## User story
As a team member, I would like an updated acquisitions roadmap so that I can plan accordingly. 
  
## Acceptance criteria
- [x] Update roadmap to include acquisition timeline information
- [x] Rebecca & Mark to sync ahead of next week’s acquisition work session
- [ ]

## Definition of done
- [x] Present / send to NSF. 
- [ ]
- [ ]
